apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cart
  template:
    metadata:
      labels:
        io.kompose.service: cart
    spec:
      containers:
      - name: cart
        image: cart:latest
        ports:
        - containerPort: 8080
