apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: robot-shop
<<<<<<< HEAD
=======
  labels:
    app: cart
>>>>>>> 8a6c13d (Your commit message)
spec:
  replicas: 1
  selector:
    matchLabels:
<<<<<<< HEAD
      io.kompose.service: cart
=======
      app: cart
>>>>>>> 8a6c13d (Your commit message)
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
<<<<<<< HEAD
        image: cart:latest
        ports:
        - containerPort: 8080
=======
        image: linuxacademycontent/rs-cart:latest
        ports:
        - containerPort: 8080
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          limits:
            cpu: "200m"
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "50Mi"

>>>>>>> 8a6c13d (Your commit message)
