apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalogue
  template:
    metadata:
      labels:
        io.kompose.service: catalogue
    spec:
      containers:
      - name: catalogue
        image: catalogue:latest
        ports:
        - containerPort: 8080
