apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dispatch
  template:
    metadata:
      labels:
        io.kompose.service: dispatch
    spec:
      containers:
      - name: dispatch
        image: dispatch:latest
        ports:
        - containerPort: 8080
