apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment
  template:
    metadata:
      labels:
        io.kompose.service: payment
    spec:
      containers:
      - name: payment
        image: payment:latest
        ports:
        - containerPort: 8080
