apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: robot-shop
<<<<<<< HEAD
=======
  labels:
    app: ratings
>>>>>>> 8a6c13d (Your commit message)
spec:
  replicas: 1
  selector:
    matchLabels:
<<<<<<< HEAD
      io.kompose.service: ratings
=======
      app: ratings
>>>>>>> 8a6c13d (Your commit message)
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings
<<<<<<< HEAD
        image: ratings:latest
        ports:
        - containerPort: 8080
=======
        image: linuxacademycontent/rs-ratings:latest
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: "200m"
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "50Mi"

>>>>>>> 8a6c13d (Your commit message)
