apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ratings
  template:
    metadata:
      labels:
        io.kompose.service: ratings
    spec:
      containers:
      - name: ratings
        image: ratings:latest
        ports:
        - containerPort: 8080
