apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shipping
  template:
    metadata:
      labels:
        io.kompose.service: shipping
    spec:
      containers:
      - name: shipping
        image: shipping:latest
        ports:
        - containerPort: 8080
