apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  template:
    metadata:
      labels:
        io.kompose.service: user
    spec:
      containers:
      - name: user
        image: user:latest
        ports:
        - containerPort: 8080
